In [ ]:
import numpy as np
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

In [ ]:
data = pd.read_csv("/content/play_tennis.csv")

In [ ]:
data

day   outlook  temp humidity    wind play
0    D1     Sunny   Hot     High    Weak   No
1    D2     Sunny   Hot     High  Strong   No
2    D3  Overcast   Hot     High    Weak  Yes
3    D4      Rain  Mild     High    Weak  Yes
4    D5      Rain  Cool   Normal    Weak  Yes
5    D6      Rain  Cool   Normal  Strong   No
6    D7  Overcast  Cool   Normal  Strong  Yes
7    D8     Sunny  Mild     High    Weak   No
8    D9     Sunny  Cool   Normal    Weak  Yes
9   D10      Rain  Mild   Normal    Weak  Yes
10  D11     Sunny  Mild   Normal  Strong  Yes
11  D12  Overcast  Mild     High  Strong  Yes
12  D13  Overcast   Hot   Normal    Weak  Yes
13  D14      Rain  Mild     High  Strong   No

In [ ]:
data.shape

(14, 6)

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14 entries, 0 to 13
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype 
---  ------    --------------  ----- 
 0   day       14 non-null     object
 1   outlook   14 non-null     object
 2   temp      14 non-null     object
 3   humidity  14 non-null     object
 4   wind      14 non-null     object
 5   play      14 non-null     object
dtypes: object(6)
memory usage: 800.0+ bytes


In [ ]:
# Now we will take few input features and play as the output columns

In [ ]:
# input features
X = data.iloc[:,[2,3]]
y = data.iloc[:,5]

In [ ]:
X

temp humidity
0    Hot     High
1    Hot     High
2    Hot     High
3   Mild     High
4   Cool   Normal
5   Cool   Normal
6   Cool   Normal
7   Mild     High
8   Cool   Normal
9   Mild   Normal
10  Mild   Normal
11  Mild     High
12   Hot   Normal
13  Mild     High

In [ ]:
y

0      No
1      No
2     Yes
3     Yes
4     Yes
5      No
6     Yes
7      No
8     Yes
9     Yes
10    Yes
11    Yes
12    Yes
13     No
Name: play, dtype: object

In [ ]:
# applying the one-hot-encoding

In [ ]:
X = pd.get_dummies(X, drop_first = True)
y = pd.get_dummies(y, drop_first = True )

In [ ]:
X

temp_Hot  temp_Mild  humidity_Normal
0          1          0                0
1          1          0                0
2          1          0                0
3          0          1                0
4          0          0                1
5          0          0                1
6          0          0                1
7          0          1                0
8          0          0                1
9          0          1                1
10         0          1                1
11         0          1                0
12         1          0                1
13         0          1                0

In [ ]:
y

Yes
0     0
1     0
2     1
3     1
4     1
5     0
6     1
7     0
8     1
9     1
10    1
11    1
12    1
13    0

In [ ]:
# train_test_split
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test = train_test_split(X,y, test_size = 0.25, random_state = 0 )

In [ ]:
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(10, 3)
(4, 3)
(10, 1)
(4, 1)


In [ ]:
# Applying Standard Scaler
from sklearn.preprocessing import StandardScaler

In [ ]:
sc = StandardScaler()
X_train_sc = sc.fit_transform(X_train)
X_test_sc = sc.transform(X_test)

In [ ]:
X_train_sc

array([[ 1.22474487, -1.        , -0.81649658],
       [-0.81649658,  1.        , -0.81649658],
       [-0.81649658,  1.        ,  1.22474487],
       [ 1.22474487, -1.        , -0.81649658],
       [-0.81649658,  1.        , -0.81649658],
       [-0.81649658,  1.        ,  1.22474487],
       [-0.81649658,  1.        , -0.81649658],
       [ 1.22474487, -1.        , -0.81649658],
       [-0.81649658, -1.        ,  1.22474487],
       [ 1.22474487, -1.        ,  1.22474487]])

In [ ]:
# input data should be in 2D format whether in the array or dataframe

In [ ]:
from sklearn.naive_bayes import GaussianNB
model1 = GaussianNB()
model1.fit(X_train_sc, y_train)

GaussianNB()

In [ ]:
# now lets predict the values
y_pred = model1.predict(X_test_sc)
y_pred

array([1, 1, 1, 0], dtype=uint8)

In [ ]:
y_test

Yes
8     1
6     1
4     1
11    1

In [ ]:
# performance of the model
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [ ]:
acc = accuracy_score(y_test, y_pred)
print(acc)

0.75


In [ ]:
confusion_matrix(y_test,y_pred)

array([[0, 0],
       [1, 3]])

In [ ]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.00      0.00      0.00         0
           1       1.00      0.75      0.86         4

    accuracy                           0.75         4
   macro avg       0.50      0.38      0.43         4
weighted avg       1.00      0.75      0.86         4

