In [ ]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')


In [ ]:
#Now we are importing the dataset
data=pd.read_csv('/content/Learner_marks_record.csv')

In [ ]:
data.head()

Hours_to_study  Obtained_Marks
0            6.83           78.50
1            6.56           76.74
2             NaN           78.68
3            5.67           71.82
4            8.67           84.19

In [ ]:
#checking the null values 
data.isnull().sum()

Hours_to_study    5
Obtained_Marks    0
dtype: int64

In [ ]:
#Basically we have very less null values so we can ignore this 
data1=data.dropna()

In [ ]:
data1.isnull().sum()

Hours_to_study    0
Obtained_Marks    0
dtype: int64

In [ ]:
#now all the null values have been dropped now we can proceed we the next steps of modeling..
#Now we are checking the object of data
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 2 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   Hours_to_study  195 non-null    float64
 1   Obtained_Marks  200 non-null    float64
dtypes: float64(2)
memory usage: 3.2 KB


In [ ]:
#Now we are dividing the data into two parts 
X=data1[['Hours_to_study']]

In [ ]:
X

Hours_to_study
0              6.83
1              6.56
3              5.67
4              8.67
5              7.55
..              ...
195            7.53
196            8.56
197            8.94
198            6.60
199            8.35

[195 rows x 1 columns]

In [ ]:
y=data1[['Obtained_Marks']]

In [ ]:
y

Obtained_Marks
0             78.50
1             76.74
3             71.82
4             84.19
5             81.18
..              ...
195           81.67
196           84.68
197           86.75
198           78.05
199           83.50

[195 rows x 1 columns]

In [ ]:
#now we have divided the data into 2 parts
#Now we are applying the train_test_split 
from sklearn.model_selection import train_test_split

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X,y, train_size = 0.75, random_state = 0)

In [ ]:
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(146, 1)
(49, 1)
(146, 1)
(49, 1)


In [ ]:
from sklearn.preprocessing import StandardScaler

In [ ]:
sc=StandardScaler()

In [ ]:
sc.fit(X_train)
X_train_sc=sc.transform(X_train)
X_test_sc=sc.transform(X_test)

In [ ]:
X_train_sc

array([[ 0.48717545],
       [-1.02974531],
       [ 0.70273788],
       [-1.34111326],
       [-0.12757665],
       [-1.29321049],
       [ 0.27959682],
       [-0.11959285],
       [-1.30917808],
       [ 0.27161303],
       [-1.46885395],
       [-1.48482154],
       [-1.06168048],
       [-0.26330113],
       [ 1.08595996],
       [-1.24530773],
       [-1.22135635],
       [ 1.21370066],
       [-0.56668529],
       [-1.39699981],
       [ 0.79055961],
       [-1.22934015],
       [-1.34909705],
       [ 1.48514964],
       [-0.422977  ],
       [-0.90998841],
       [-0.6704746 ],
       [ 0.49515925],
       [-1.22934015],
       [ 1.18176549],
       [ 0.35943476],
       [ 1.43724688],
       [-1.12555083],
       [ 0.14387233],
       [ 0.03209922],
       [-1.02974531],
       [-0.71837736],
       [ 1.18176549],
       [ 0.69475408],
       [-0.83015047],
       [ 0.37540234],
       [ 1.22168445],
       [ 0.97418686],
       [-1.05369669],
       [-0.7902315 ],
       [ 0

Creating Machine learning models
1.Linear regression model


In [ ]:
from sklearn.linear_model import LinearRegression
lr=LinearRegression()

In [ ]:
lr.fit(X_train_sc,y_train)

LinearRegression()

In [ ]:
y_pred=lr.predict(X_test_sc)

In [ ]:
y_pred

array([[72.65550783],
       [81.47454262],
       [78.36651274],
       [71.76194924],
       [71.72309887],
       [84.62142288],
       [70.47988691],
       [75.56928585],
       [70.63528841],
       [80.58098403],
       [70.9460914 ],
       [76.69594668],
       [75.37503398],
       [71.68424849],
       [71.72309887],
       [82.05729823],
       [78.52191424],
       [75.45273473],
       [78.01685938],
       [85.55383184],
       [71.72309887],
       [73.27711381],
       [84.19406877],
       [82.64005383],
       [71.95620111],
       [85.4761311 ],
       [81.66879449],
       [70.9460914 ],
       [78.98811872],
       [70.24678467],
       [73.51021605],
       [81.31914113],
       [70.47988691],
       [81.39684188],
       [80.11477955],
       [76.65709631],
       [84.42717101],
       [70.28563505],
       [81.3579915 ],
       [76.92904892],
       [76.0743407 ],
       [73.78216866],
       [79.57087432],
       [77.00674967],
       [80.7752359 ],
       [76

In [ ]:
lr.predict([[7.6]])

array([[115.27078878]])

In [ ]:
from sklearn.metrics import r2_score

In [ ]:
r2_score(y_test,y_pred)

0.9513121057797149

In [ ]:
from sklearn.metrics import mean_squared_error
mse=mean_squared_error(y_test,y_pred)
mse

1.1545937716607912

In [ ]:
rsme=np.sqrt(mse)
rsme

1.0745202518616348

2nd Model 

In [ ]:

#applying the decision tree 
from sklearn.tree import DecisionTreeRegressor


In [ ]:
dt=DecisionTreeRegressor()

In [ ]:
dt.fit(X_train_sc,y_train)

DecisionTreeRegressor()

In [ ]:
model2=dt.predict(X_test_sc)

In [ ]:
model2

array([73.08 , 79.1  , 78.42 , 71.1  , 71.87 , 84.235, 70.67 , 75.04 ,
       71.79 , 81.01 , 68.57 , 76.8  , 74.605, 71.8  , 71.87 , 81.74 ,
       78.42 , 74.605, 77.19 , 86.75 , 71.87 , 73.79 , 83.91 , 83.08 ,
       70.96 , 85.96 , 82.355, 68.57 , 79.64 , 70.67 , 74.25 , 81.245,
       70.67 , 79.1  , 79.64 , 76.8  , 84.19 , 70.67 , 81.245, 77.07 ,
       74.75 , 74.15 , 82.18 , 77.07 , 80.81 , 74.75 , 77.07 , 79.64 ,
       82.43 ])

In [ ]:
r2_score(y_test,model2)

0.9047319998021276

In [ ]:
#Here My model has 90% of accuracy in Decision tree regression 

In [ ]:
from sklearn.metrics import mean_squared_error

In [ ]:
mse=mean_squared_error(y_test,model2)

In [ ]:
mse

2.2592030612244947

In [ ]:
rsme = np.sqrt(mse)

In [ ]:
rsme

1.503064556572503

Model 3 

Here Iam applying KNN regressor model

In [ ]:
from sklearn.neighbors import KNeighborsRegressor

In [ ]:
model2=KNeighborsRegressor()

In [ ]:
model2.fit(X_train_sc,y_train)

KNeighborsRegressor()

In [ ]:
y_pred1=model2.predict(X_test_sc)

In [ ]:
y_pred1

array([[72.68 ],
       [81.31 ],
       [78.172],
       [71.562],
       [71.79 ],
       [84.12 ],
       [71.228],
       [75.472],
       [71.338],
       [80.098],
       [70.352],
       [76.548],
       [75.094],
       [71.744],
       [71.79 ],
       [82.388],
       [78.708],
       [75.094],
       [77.546],
       [86.14 ],
       [71.79 ],
       [73.864],
       [84.106],
       [82.816],
       [71.77 ],
       [86.204],
       [82.41 ],
       [70.352],
       [79.16 ],
       [71.228],
       [73.714],
       [81.148],
       [71.228],
       [81.44 ],
       [80.522],
       [76.674],
       [84.228],
       [71.228],
       [81.414],
       [76.724],
       [76.21 ],
       [74.1  ],
       [79.642],
       [77.072],
       [80.418],
       [76.21 ],
       [75.818],
       [78.922],
       [83.168]])

In [ ]:
r2_score(y_test,y_pred1)

0.9464305282595222

In [ ]:
#Here my model has 94% accurancy Lets calculate MSE & RMSE


In [ ]:
mse=mean_squared_error(y_test,y_pred1)

In [ ]:
mse

1.2703564081632646

In [ ]:
rmse=np.sqrt(mse)

In [ ]:
rmse

1.1271008864175667

Random forest Model 

In [ ]:
from sklearn.ensemble import RandomForestRegressor
rfr=RandomForestRegressor()

In [ ]:
rfr.fit(X_train_sc,y_train)

RandomForestRegressor()

In [ ]:
y_pred_rf=rfr.predict(X_test_sc)

In [ ]:
y_pred_rf

array([72.9294    , 79.8155381 , 78.23465095, 71.3898    , 71.7342    ,
       84.13634333, 70.86752333, 75.24725   , 71.551225  , 80.7811    ,
       69.4518069 , 76.72283333, 74.82575833, 71.7613    , 71.7342    ,
       81.8798    , 78.33265095, 74.86155833, 77.39303333, 86.48956   ,
       71.7342    , 73.63085   , 83.94976667, 83.09755   , 71.3952    ,
       86.07089333, 82.40204167, 69.4518069 , 79.55217571, 70.86752333,
       73.96305   , 81.01721643, 70.86752333, 79.8155381 , 80.27248333,
       76.68040833, 84.30753333, 70.86752333, 81.01721643, 76.98811667,
       75.3256    , 73.92605   , 81.2001    , 76.98885   , 80.7029    ,
       75.3256    , 76.5898    , 79.46217238, 82.58101667])

In [ ]:
r2_score(y_test,y_pred_rf)

0.9283185434339423

In [ ]:
# Here my model has 92% accuracy Now we are calculating MSE and RMSE


In [ ]:
mse=mean_squared_error(y_test,y_pred_rf)

In [ ]:
mse

1.6998673822344479

In [ ]:
rmse=np.sqrt(mse)

In [ ]:
rmse

1.3037896234571158

In [ ]:
import joblib

In [ ]:
joblib.dump(lr,"Regressionmodel.pkl")

['Regressionmodel.pkl']