In [ ]:
# we are going to start the coding for the random forest.
# it is an ensemble learning technique.

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
data = pd.read_csv("/content/employees.csv")

In [ ]:
data

satisfactoryLevel  lastEvaluation  numberOfProjects  avgMonthlyHours  \
0                   0.38            0.53                 2              157   
1                   0.80            0.86                 5              262   
2                   0.11            0.88                 7              272   
3                   0.37            0.52                 2              159   
4                   0.41            0.50                 2              153   
...                  ...             ...               ...              ...   
14994               0.11            0.85                 7              275   
14995               0.99            0.83                 4              274   
14996               0.72            0.72                 4              175   
14997               0.24            0.91                 5              177   
14998               0.77            0.83                 6              271   

       timeSpent.company  workAccident  left  promotionInLast5years  \
0                      3             0     1                      0   
1                      6             0     1                      0   
2                      4             0     1                      0   
3                      3             0     1                      0   
4                      3             0     1                      0   
...                  ...           ...   ...                    ...   
14994                  4             0     1                      0   
14995                  2             0     0                      0   
14996                  4             0     0                      0   
14997                  5             0     0                      0   
14998                  3             0     0                      0   

            dept  salary  
0          sales     low  
1          sales  medium  
2          sales  medium  
3          sales     low  
4          sales     low  
...          ...     ...  
14994    support  medium  
14995      sales     low  
14996  technical     low  
14997      sales     low  
14998    support     low  

[14999 rows x 10 columns]

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14999 entries, 0 to 14998
Data columns (total 10 columns):
 #   Column                 Non-Null Count  Dtype  
---  ------                 --------------  -----  
 0   satisfactoryLevel      14999 non-null  float64
 1   lastEvaluation         14999 non-null  float64
 2   numberOfProjects       14999 non-null  int64  
 3   avgMonthlyHours        14999 non-null  int64  
 4   timeSpent.company      14999 non-null  int64  
 5   workAccident           14999 non-null  int64  
 6   left                   14999 non-null  int64  
 7   promotionInLast5years  14999 non-null  int64  
 8   dept                   14999 non-null  object 
 9   salary                 14999 non-null  object 
dtypes: float64(2), int64(6), object(2)
memory usage: 1.1+ MB


In [ ]:
# null values
data.isnull().sum()

satisfactoryLevel        0
lastEvaluation           0
numberOfProjects         0
avgMonthlyHours          0
timeSpent.company        0
workAccident             0
left                     0
promotionInLast5years    0
dept                     0
salary                   0
dtype: int64

In [ ]:
# input and output data

In [ ]:
X = data[['satisfactoryLevel','lastEvaluation','numberOfProjects','avgMonthlyHours',
          'timeSpent.company','workAccident','promotionInLast5years']]

In [ ]:
X

satisfactoryLevel  lastEvaluation  numberOfProjects  avgMonthlyHours  \
0                   0.38            0.53                 2              157   
1                   0.80            0.86                 5              262   
2                   0.11            0.88                 7              272   
3                   0.37            0.52                 2              159   
4                   0.41            0.50                 2              153   
...                  ...             ...               ...              ...   
14994               0.11            0.85                 7              275   
14995               0.99            0.83                 4              274   
14996               0.72            0.72                 4              175   
14997               0.24            0.91                 5              177   
14998               0.77            0.83                 6              271   

       timeSpent.company  workAccident  promotionInLast5years  
0                      3             0                      0  
1                      6             0                      0  
2                      4             0                      0  
3                      3             0                      0  
4                      3             0                      0  
...                  ...           ...                    ...  
14994                  4             0                      0  
14995                  2             0                      0  
14996                  4             0                      0  
14997                  5             0                      0  
14998                  3             0                      0  

[14999 rows x 7 columns]

In [ ]:
y = data['left']

In [ ]:
y

0        1
1        1
2        1
3        1
4        1
        ..
14994    1
14995    0
14996    0
14997    0
14998    0
Name: left, Length: 14999, dtype: int64

In [ ]:
# train_test_split

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X,y, train_size = 0.75, random_state = 0)

In [ ]:
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(11249, 7)
(3750, 7)
(11249,)
(3750,)


In [ ]:
# Applying the standard Scaler
from sklearn.preprocessing import StandardScaler

In [ ]:
sc = StandardScaler()
sc.fit(X_train)
X_train_sc = sc.transform(X_train)
X_test_sc = sc.transform(X_test)

In [ ]:
X_train_sc

array([[ 1.40042252, -0.50010765,  0.15986946, ...,  0.33636292,
        -0.41179834, -0.14733478],
       [ 0.99725847,  1.02014933, -0.65203643, ..., -1.02127846,
        -0.41179834, -0.14733478],
       [-0.65571412, -1.02635045, -1.46394232, ..., -0.34245777,
        -0.41179834, -0.14733478],
       ...,
       [ 0.47314521,  1.66333497,  0.15986946, ...,  1.01518361,
        -0.41179834, -0.14733478],
       [-2.02647188,  0.9616779 ,  2.59558712, ...,  0.33636292,
        -0.41179834, -0.14733478],
       [ 0.15061397, -1.31870756,  0.15986946, ...,  0.33636292,
        -0.41179834, -0.14733478]])

In [ ]:
X_test_sc

array([[ 1.31978971,  1.02014933,  0.15986946, ..., -0.34245777,
        -0.41179834, -0.14733478],
       [ 1.36010611, -0.55857907,  0.15986946, ..., -1.02127846,
        -0.41179834, -0.14733478],
       [-0.41381569, -0.96787902, -1.46394232, ...,  2.37282499,
        -0.41179834,  6.78726348],
       ...,
       [-0.09128445,  0.20154942,  0.15986946, ..., -0.34245777,
        -0.41179834, -0.14733478],
       [-2.02647188,  1.19556359,  2.59558712, ...,  0.33636292,
        -0.41179834, -0.14733478],
       [ 1.11820769,  1.66333497,  0.97177535, ...,  1.01518361,
        -0.41179834, -0.14733478]])

In [ ]:
# applying random forest
from sklearn.ensemble import RandomForestClassifier

In [ ]:
model1 = RandomForestClassifier(n_estimators = 100)
# default value of n_estimators in 100

In [ ]:
model1.fit(X_train_sc,y_train)


RandomForestClassifier()

In [ ]:
y_pred = model1.predict(X_test_sc)

In [ ]:
y_pred

array([0, 0, 0, ..., 0, 1, 1])

In [ ]:
y_pred_df = pd.DataFrame(y_pred)

In [ ]:
y_pred_df.value_counts()

0    2859
1     891
dtype: int64

In [ ]:
# performance
from sklearn.metrics import confusion_matrix, classification_report,accuracy_score

In [ ]:
confusion_matrix(y_test,y_pred)

array([[2833,    4],
       [  26,  887]])

In [ ]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.99      1.00      0.99      2837
           1       1.00      0.97      0.98       913

    accuracy                           0.99      3750
   macro avg       0.99      0.99      0.99      3750
weighted avg       0.99      0.99      0.99      3750

